Feature/update template
Eastern-Research-Group/lew pull request #131
Opened 2023-12-27 18:47 UTC by maxdiebold-erg

## Main Changes:
* Updated to the newest [EPA template](https://www.epa.gov/themes/epa_theme/pattern-lab/?p=pages-standalone-template), caching all required external files and removing inapplicable code.

## Steps To Test:
1. Test all pages locally (`index.html`, `400.html`, `500.html`, `api_key_signup.html`, & `api-docs/index.html`), and verify everything functions correctly in the context of the new template.

2023-12-27 21:40 UTC, maxdiebold-erg commented
I need to address a font issue before I missed, then I will reopen this.

2024-01-02 16:00 UTC, cschwinderg requested changes
The header and footer looks good. 

I'm seeing some style changes in other areas (screenshots below left = new and right = production).

* The results panel now takes up the full width and the R Factor value looks a little different. This one is might be ok though. @coobr01 What is your opinion on this one? Personally, I like that the new version takes up the full width.
![image](https://github.com/Eastern-Research-Group/lew/assets/46329268/f6d251d5-5c2b-4bd4-a6b6-53570568f54f)

* The api docs page now has grids around the table cells. I think this one needs to be fixed.
![image](https://github.com/Eastern-Research-Group/lew/assets/46329268/e96fe203-09ce-4098-9c0e-a603009b6f7c)

2024-01-02 17:29 UTC, maxdiebold-erg commented on app/app/public/400.html
> +                  >
I think the one on the right is `500.html` and the left is `400.html`? I'd just copied the content over for both.

2024-01-02 17:30 UTC, maxdiebold-erg commented
@cschwinderg Good catches, I'll fix the styles on the API documentation page.

2024-01-02 18:02 UTC, cschwinderg commented on app/app/public/400.html
> +                  >
You are correct. Thanks for catching that.

2024-01-02 18:12 UTC, cschwinderg requested changes
I found one more issue. The responses table has a different header styles. 

Production also has a white box around `Media type` dropdown, but I think our new version looks better. It was also probably just a conflict with the old epa template.

Left=new | right=production
![image](https://github.com/Eastern-Research-Group/lew/assets/46329268/e0aa0980-b931-4b93-b513-b3f78e45410b)

2024-01-02 19:16 UTC, maxdiebold-erg commented
That last issue should be fixed, and the R factor number should look closer to production's (the number's color is a bit different, as is the surrounding shaded box: I thought it would be more consistent to stick with theme colors).

2024-01-02 19:55 UTC, cschwinderg approved these changes
Looks good! Thanks for making those changes!

2024-01-02 19:55 UTC, merged